In [1]:
import jax
import jax.numpy as jnp

In [20]:
def cost(x, y):
    error = 0
    for i in range(len(x)):
        error += ((x[i - 1] * y[i] / y[i - 1]) - y[i - 1]) ** 2
    return jnp.sum((x - y) ** 2)

In [21]:
gt = jnp.array([1.0, 2.0, 3.0, 4.0, 5.0])
pred = jnp.array([0.0, 0.0, 0.0, 0.0, 0.0])

In [22]:
grad_cost = jax.grad(cost)

In [23]:
for i in range(20):
    pred = pred - 0.1 * grad_cost(pred, gt)
    print(pred)

[0.2 0.4 0.6 0.8 1. ]
[0.36 0.72 1.08 1.44 1.8 ]
[0.48800004 0.9760001  1.464      1.9520001  2.44      ]
[0.59040004 1.1808001  1.7712     2.3616002  2.9520001 ]
[0.67232   1.34464   2.01696   2.68928   3.3616002]
[0.73785603 1.4757121  2.213568   2.9514241  3.68928   ]
[0.7902848 1.5805696 2.3708544 3.1611392 3.9514241]
[0.8322278 1.6644557 2.4966836 3.3289113 4.1611395]
[0.86578226 1.7315645  2.5973468  3.463129   4.328912  ]
[0.8926258 1.7852516 2.6778774 3.5705032 4.4631295]
[0.91410065 1.8282013  2.742302   3.6564026  4.5705037 ]
[0.9312805 1.862561  2.7938416 3.725122  4.656403 ]
[0.9450244 1.8900487 2.8350732 3.7800975 4.7251225]
[0.9560195 1.912039  2.8680587 3.824078  4.780098 ]
[0.9648156 1.9296312 2.8944468 3.8592625 4.8240786]
[0.9718525 1.943705  2.9155574 3.88741   4.859263 ]
[0.97748196 1.9549639  2.932446   3.9099278  4.88741   ]
[0.98198557 1.9639711  2.9459567  3.9279423  4.9099283 ]
[0.98558843 1.9711769  2.9567654  3.9423537  4.9279428 ]
[0.98847073 1.9769415  2.96